name: Windows Cloud Desktop

on:
  workflow_dispatch:

jobs:
  desktop:
    runs-on: windows-latest

    steps:
      - name: Keep Windows runner alive
        run: |
          Write-Host "Windows Cloud Desktop aktif"
          while ($true) {
            Start-Sleep -Seconds 60
          }
